### ISSUE TITLE
userside_php_1 не запускается

### ISSUE THREAD

**Issue by chatlamin** [userside/userside-docker#2]
После обновления 3.13 до версии 3.16 контейнер userside_php_1 не запускается. 
`docker logs userside_php_1` сообщает
```
Interactive shell
```

**Comment by chatlamin** [comment]
Возможно это имеет отношение к проблеме: на главной странице userside следующие ошибки:

```
ВНИМАНИЕ
Не работает планировщик ERP "UserSide". Последний запуск: 12.08.2021 19:34:41
ВНИМАНИЕ
Не работает планировщик фреймворка. Последний запуск: 12.08.2021 19:34:41
```

**Comment by chatlamin** [comment]
> Возможно это имеет отношение к проблеме: на главной странице userside следующие ошибки:

это было из-за старой версии docker-compose. обновил - проблема решилась.
было `docker-compose version 1.22.0, build f46880fe`
стало `docker-compose version 1.29.2, build 5becea4c`

**Comment by chatlamin** [comment]
Проверил на чистой инсталляции, тоже самое. Контейнер userside_php_1 не запускается.
`docker logs userside_php_1` сообщает
```
Interactive shell
```

**Comment by denisbondar** [comment]
В версии 3.13 у нас использовался только `php-fpm` и контейнер назывался **fpm**. Все консольные команды запускались внутри этого одного контейнера.
Начиная с версии 3.16 теперь мы используем отдельный контейнер **php** на базе `php-cli` с целью запуска всех консольных команд в нем — мы собрали все необходимые зависимости на базе `php-cli` в Docker-образ `erpuserside/userside:3.16-php`. Это разделение связано с тем, что теперь у нас есть фоновые процессы ядра, которые работают используя образ `erpuserside/userside:3.16-php` на базе php-cli и использовать для этих целей **fpm** неправильно.
Образ erpuserside/userside:3.16-php не имеет команды запуска, так как каждый раз он запускается с разной командой. Поэтому при запуске контейнера ничего не происходит — он завершает свою работу. Он и не должен быть запущен постоянно. Он работает только тогда, когда в нём что-то выполняется, а затем он завершает свою работу.
