### ISSUE TITLE
Неименованные тома в версии 3.16

### ISSUE THREAD

**Issue by chatlamin** [userside/userside-docker#3]
Появилось 5 неименованных томов

`docker volume ls` возвращает

```
DRIVER              VOLUME NAME
local               243c1473b02e32074ee06d017828a941d36c31ad3f343c07f81a9bd25a65046b
local               2f1f7b16252edeb29bcc1cdd29185f7d4aefa6014e7aa349961f8c3a5465ba48
local               4a9a50451d26b2aef3cfbec5484036ca7e78bf4f33ae82443a7947862bf445f1
local               a0540cbd18952e0e5e587f828e986675cb0ff6dd6c9b350f6cb96befbdbc65cf
local               d5fab487e7b8bc39d1f9e73166bbcdf1fd5b5ee18a5af4daade518e3479d522c
local               userside_backup
local               userside_db
local               userside_rabbitmq
local               userside_redis
local               userside_www
```
Похоже они принадлежат контейнерам userside_core-worker_№№
Мне кажется, тома без имени типа `243c1473b02e32074ee06d017828a941d36c31ad3f343c07f81a9bd25a65046b` плохая практика. Они могут плодится, захламляя собой систему после каждого обновления или пересоздания docker-compose.

**Comment by denisbondar** [comment]
Далеко не все тома имеют имена. Это нормально.
Тома для контейнеров core-worker используются следующие:
```
volumes:
  - www:/app/userside
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
```
Первый том — именованный том **www**.
Второй и третий — не именованные. Это файлы часового пояса и временной зоны. Монтируются в режиме чтения внутрь каждого контейнера, чтобы время совпадало везде.

Томов без имени всегда фактически значительно больше, чем с именем. Разницы никакой нет. Не именованные тома удаляются всегда при удалении бандла через `docker-compose down`, а именованные удаляются только при использовании дополнительной опции `docker-compose down -v`.

Makefile содержит макрос `uninstall`, который удаляет все тома и даже брошенные контейнеры, если они есть.
