### ISSUE TITLE
In bundle.bash-example incorrect path to docker-compose

### ISSUE THREAD

**Issue by baralgin584** [userside/userside-docker#4]
In file _bundle.bash-example_ incorrect path to docker-compose

"DOCKER_COMPOSE="sudo /usr/bin/docker compose -p ${PROJECT_NAME}""
missing "-" in "docker compose", and for example in Debian

```
# whereis docker-compose
docker-compose: /usr/local/bin/docker-compose
```

**Comment by denisbondar** [comment]
Sorry, didn't get the issue notification.

The hyphen was necessary when compose was a separate `docker-compose` binary file.

Since version 2, it is a Docker plugin that should be called like this: `docker compose`.

**Comment by denisbondar** [comment]
Close
